/* Quiz sections and comparison UI. Domain calculations live in core.js. */
let analysisOpen=false,analysisState={type:'student',ids:[],metric:'rate',content:'total',showClassAverage:true,showGradeAverage:true,keys:null,from:'',to:''};
const profileTrends=new Map();
function profileTrend(sid){if(!profileTrends.has(sid))profileTrends.set(sid,{type:'student',ids:[sid],metric:'gradeRank',content:'total',showClassAverage:true,showGradeAverage:true,keys:null});return profileTrends.get(sid);}
function trendConfig(profile=false){return profile?{...profileTrend(studentId),from,to}:analysisState;}
function profileModel(sid,mode=trendMode){return T.trendData(data,{...profileTrend(sid),metric:mode,from,to});}
function sectionInputs(sections={}){return `<div class="section-config">${T.sectionNames.map(n=>`<label class="field"><span>${n}</span><input type="number" min="0.01" step="any" placeholder="不分项" data-section-max="${n}" aria-label="${n}满分" value="${sections[n]??''}"></label>`).join('')}</div>`;}
function readSections(form){return Object.fromEntries([...form.querySelectorAll('[data-section-max]')].filter(el=>el.value!=='').map(el=>[el.dataset.sectionMax,Number(el.value)]));}
function sectionsDialog(a){modal('设置题型分项',`<form id="sections-form" data-id="${a.id}"><p class="help">为需要统计的题型填写满分，留空表示不分项。总成绩独立录入，不自动求和；已有成绩的分项不能直接移除。</p>${sectionInputs(a.sections)}<div class="dialog-actions">${btn('取消','close')}<button class="primary">保存分项设置</button></div></form>`,true);}
function sectionScoreInputs(a,r){return Object.entries(a.sections||{}).map(([name,max])=>`<label class="field"><span>${name} / ${max}</span><input type="number" min="0" max="${max}" step="any" data-record="${r.id}" data-section-score="${name}" aria-label="${esc(nameOf(r.studentId))} ${name}" placeholder="未录入" value="${r.sectionScores?.[name]??''}" ${r.status==='absent'?'disabled':''}></label>`).join('');}
function sectionPanel(a){const names=Object.keys(a.sections||{});if(!names.length)return `<p class="help">本场未设置题型分项，可点击「题型分项」选择需要记录的内容。</p>`;
  return `<details class="section-details"><summary>查看题型分项均分 · ${names.length} 项</summary><div class="table-wrap"><table><thead><tr><th>题型</th><th>满分</th><th>班级均分</th><th>班级平均得分率</th><th>有效人数</th><th>待录入</th></tr></thead><tbody>${names.map(n=>{const st=T.contentStats(data,a,n);return `<tr><td>${n}</td><td>${a.sections[n]}</td><td>${scoreMean(st.classAverage)}</td><td>${pct(st.classAverage===null?null:st.classAverage/a.sections[n]*100)}</td><td>${st.classCount}</td><td>${st.classBlank}</td></tr>`;}).join('')}</tbody></table></div></details><details class="section-details"><summary>登记 / 查看学生分项成绩</summary><p class="help">留空表示未录入；清空已有单元格会删除该项成绩。缺考不参与统计。总成绩在主表独立录入。</p><div class="table-wrap"><table class="section-score-table"><thead><tr><th>学生</th>${names.map(n=>`<th>${n}<br><span class="help">满分 ${a.sections[n]}</span></th>`).join('')}</tr></thead><tbody>${recordRows(a).map(({r,s})=>`<tr><th>${esc(s.name)}<div class="help">${esc(s.number)}</div></th>${names.map(n=>`<td><input type="number" step="any" min="0" max="${a.sections[n]}" aria-label="${esc(s.name)} ${n}" data-record="${r.id}" data-section-score="${n}" value="${r.sectionScores?.[n]??''}" ${r.status==='absent'?'disabled':''}></td>`).join('')}</tr>`).join('')}</tbody></table></div></details>`;
}
function gradeRows(a,query='',cls=''){const q=quizInfo(a);return q.group.flatMap(act=>act.studentIds.map(id=>({a:act,r:T.record(data,act.id,id),s:data.students.find(s=>s.id===id),rank:q.gradeRanks.get(id)}))).filter(x=>(!cls||x.a.classId===cls)&&(!query||`${x.s.name} ${x.s.number} ${className(x.a.classId)}`.includes(query))).sort((x,y)=>(x.rank??Infinity)-(y.rank??Infinity)||className(x.a.classId).localeCompare(className(y.a.classId),'zh',{numeric:true})||x.s.number.localeCompare(y.s.number,'zh',{numeric:true})||x.s.name.localeCompare(y.s.name,'zh'));}
let gradeSelection={id:'',query:'',cls:''};
function gradeRankingBody(a){const q=quizInfo(a),rows=gradeRows(a,gradeSelection.query,gradeSelection.cls);return `<p class="help">${q.group.map(x=>esc(className(x.classId))).join('、')} · ${q.gradeCount} 人有效，${q.gradeBlank} 人待录入。${q.gradeBlank?'名次暂定。':''}名次始终按总成绩，筛选不会重新排名。</p><div class="toolbar"><input id="grade-search" type="search" aria-label="搜索年级排名" placeholder="姓名、学号或班级" value="${esc(gradeSelection.query)}"><select id="grade-class" aria-label="排名班级筛选">${option('','全部关联班级',gradeSelection.cls)}${q.group.map(x=>option(x.classId,className(x.classId),gradeSelection.cls)).join('')}</select>${btn('导出融合排名','export-grade',`data-id="${a.id}"`)}</div><div class="table-wrap"><table><thead><tr><th>年级名次</th><th>班级</th><th>姓名 / 学号</th><th>总成绩</th><th>考试日期</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.rank??'—'}</td><td>${esc(className(x.a.classId))}</td><td>${esc(x.s.name)}<div class="help">${esc(x.s.number)}</div></td><td>${x.r.status==='score'?`${x.r.score} / ${x.a.total}`:x.r.status==='absent'?'缺考':'未录入'}</td><td>${x.a.date}</td></tr>`).join('')}</tbody></table></div>`;}
function gradeDialog(id){const a=data.activities.find(x=>x.id===id);if(gradeSelection.id!==id)gradeSelection={id,query:'',cls:''};modal(`${esc(a.name)} · 关联班级融合排名`,`<div id="grade-ranking">${gradeRankingBody(a)}</div>`,true);}
function progressMarkup(a,r,keys=null,start=view==='students'?from:'',end=view==='students'?to:''){const effectiveKeys=keys===null&&view==='students'&&studentId?profileTrend(studentId).keys:keys,change=T.rankChange(data,a,r,effectiveKeys,start,end);return change?`<span class="${change.value>0?'improved':change.value<0?'error-text':''}">${diff(change.value)}</span><div class="help">对比 ${esc(change.previous.name)} · ${change.previous.date}<br>${change.beforeRank}/${change.beforeCount} 人 → ${change.rank}/${change.count} 人</div>`:'<span class="help">暂无可比数据</span>';}
const chartColors=['#7956b3','#2b8e91','#c16b4f','#5773bd','#a7508d','#668345','#b28328','#745950'];
function comparisonChart(model){const {points,series,metric,content}=model;if(!points.length)return empty('暂无可绘制场次','选择学生或班级，再选择需要比较的小测；跨班比较需先关联场次。');
  const ranked=metric==='gradeRank',raw=metric==='average',w=900,h=320,pad=64,bottom=68,plotHeight=h-bottom-28;
  const values=series.flatMap(s=>s.points.filter(p=>p&&p.value!=null).map(p=>p.value)),max=ranked?Math.max(1,...points.map(p=>p.ranks.gradeCount)):raw?Math.max(1,...points.flatMap(p=>p.group.map(a=>T.contentMax(a,content)||0)),...values):100;
  const x=i=>points.length===1?w/2:pad+i*(w-2*pad)/(points.length-1),y=v=>ranked?28+(v-1)/Math.max(1,max-1)*plotHeight:h-bottom-v/max*plotHeight;
  const ticks=ranked?[...new Set([1,...[.25,.5,.75,1].map(v=>Math.round(1+(max-1)*v))])]:[0,.25,.5,.75,1].map(v=>max*v);
  const label=value=>ranked?`第 ${value} 名`:raw?Number(value.toFixed(2))+'分':value.toFixed(1)+'%';
  return `<div class="chart-block"><p class="help">${ranked?'总成绩 · 年级名次（第 1 名在上方）':`${content==='total'?'总成绩':content} · ${raw?'班级均分（不同满分建议切换平均得分率）':'得分率'}`} · ${points.length} 场</p><div class="chart-legend">${series.map((s,i)=>`<span><i style="background:${chartColors[i%chartColors.length]}"></i>${esc(s.label)}${s.role==='student'?`（${esc(className(data.students.find(x=>x.id===s.id)?.classId))} · ${esc(data.students.find(x=>x.id===s.id)?.number||'无学号')}）`:''}</span>`).join('')}</div><svg class="chart comparison-chart" viewBox="0 0 ${w} ${h}" data-metric="${metric}" role="img" aria-label="${ranked?'总成绩年级名次':content+'成绩'}对比图"><title>${ranked?'总成绩年级名次':content==='total'?'总成绩':content}趋势</title>${ticks.map(v=>`<line class="grid" x1="${pad}" x2="${w-pad}" y1="${y(v)}" y2="${y(v)}"/><text x="2" y="${y(v)+4}">${label(v)}</text>`).join('')}${series.map((s,si)=>{const color=chartColors[si%chartColors.length],segments=[];let segment=[];s.points.forEach((p,i)=>{if(p&&p.value!=null)segment.push(`${x(i)},${y(p.value)}`);else if(segment.length){segments.push(segment);segment=[];}});if(segment.length)segments.push(segment);return segments.map(seg=>`<polyline fill="none" stroke="${color}" stroke-width="2.4" ${s.role==='grade'?'stroke-dasharray="3 5"':s.role==='class'&&model.type==='student'?'stroke-dasharray="8 5"':''} points="${seg.join(' ')}"/>`).join('')+s.points.map((p,i)=>p&&p.value!=null?`<circle tabindex="0" class="trend-dot" fill="${color}" cx="${x(i)}" cy="${y(p.value)}" r="4"><title>${esc(s.label)}${s.role==='student'?'（'+esc(className(p.classId))+' · '+esc(data.students.find(x=>x.id===s.id)?.number||'无学号')+'）':''} · ${esc(points[i].label)} · ${points[i].date}：${label(p.value)}；${p.score.toFixed(2)} / ${p.max} 分${ranked?'；年级 '+p.value+' / '+p.count+' 人':'；有效 '+(p.count??p.classCount)+' 人'}${p.blank?'；数据未齐，统计暂定':''}${p.change?'；'+diff(p.change.value)+'，对比 '+esc(p.change.previous.name)+' '+p.change.previous.date:''}</title></circle>`:'').join('');}).join('')}${points.map((p,i)=>i%Math.max(1,Math.ceil(points.length/7))===0||i===points.length-1?`<text x="${x(i)}" y="${h-43}" text-anchor="middle">${p.date.slice(5)}</text><text x="${x(i)}" y="${h-24}" text-anchor="middle">${esc(p.label.length>9?p.label.slice(0,8)+'…':p.label)}</text>`:'').join('')}</svg>${!values.length?'<p class="help">所选场次暂无有效成绩；年级数据需至少关联两个班级。</p>':''}<p class="help">缺失成绩保留空点并断线；年级范围仅含关联班级。悬停或聚焦数据点可查看成绩详情。</p></div>`;
}
function comparisonDetails(model,opened=false){return `<details class="trend-details" ${opened?'open':''}><summary>查看所选场次明细与总成绩名次进步</summary>${model.points.map((p,i)=>`<div class="trend-detail-item"><h3>${esc(p.label)} · ${p.date}</h3><p class="help">${p.group.map(a=>`${esc(className(a.classId))}：${a.date}，${model.content==='total'?'总分':model.content+'满分'} ${T.contentMax(a,model.content)??'未设置'}`).join('；')}。${p.group.length<2?'未关联，年级数据不可用。':''}</p><table><thead><tr><th>对象</th><th>所选内容</th><th>统计情况</th>${model.type==='student'?'<th>总成绩年级名次进步</th>':''}</tr></thead><tbody>${model.series.map(s=>{const v=s.points[i],a=s.role==='student'?p.group.find(a=>a.studentIds.includes(s.id)):null,r=a&&T.record(data,a.id,s.id);return `<tr><td>${esc(s.label)}${a?`<div class="help">${esc(className(a.classId))} · ${esc(data.students.find(x=>x.id===s.id)?.number||'无学号')}</div>`:''}</td><td>${v&&v.value!=null?`${v.score.toFixed(2)} / ${v.max}${model.metric==='gradeRank'?` · 年级 ${v.value}/${v.count} 人`:model.metric==='rate'?` · ${v.value.toFixed(1)}%`:''}`:'暂无数据'}</td><td>${v?`有效 ${v.count??v.classCount} 人${v.blank?' · 数据未齐，暂定':''}`:'—'}</td>${model.type==='student'?`<td>${r?progressMarkup(a,r,model.selectedKeys,'',''):'—'}</td>`:''}</tr>`;}).join('')}</tbody></table></div>`).join('')}</details>`;}
function comparisonControls(config,profile=false){const model=T.trendData(data,config),idPrefix=profile?'profile':'analysis';return `<div class="toolbar"><label>统计内容 <select data-trend="content" data-profile="${profile}" ${config.metric==='gradeRank'?'disabled':''}>${option('total','总成绩',config.metric==='gradeRank'?'total':config.content)}${T.sectionNames.map(n=>option(n,n,config.metric==='gradeRank'?'total':config.content)).join('')}</select></label><label>统计维度 <select ${profile?'id="trend-mode"':''} data-trend="metric" data-profile="${profile}">${(config.type==='class'?[['rate','班级平均得分率'],['average','班级均分']]:[['rate','得分率＋班级／年级均线'],['gradeRank','总成绩年级名次']]).map(([v,t])=>option(v,t,config.metric)).join('')}</select></label>${config.metric==='gradeRank'?'<span class="help">年级名次始终按总成绩</span>':''}</div>${config.type==='student'&&config.metric==='rate'?`<div class="toolbar mean-toggles"><span class="help">叠加均线</span><label><input type="checkbox" data-trend="showClassAverage" data-profile="${profile}" ${config.showClassAverage!==false?'checked':''}> 班级平均得分率</label><label><input type="checkbox" data-trend="showGradeAverage" data-profile="${profile}" ${config.showGradeAverage!==false?'checked':''}> 年级平均得分率</label></div>`:''}<details class="exam-picker"><summary>选择小测 · 已选 ${model.points.length} / ${model.eligible.length} 场</summary><div class="row">${btn('全选','trend-select-all',`data-profile="${profile}"`,'small')}${btn('清空选择','trend-select-none',`data-profile="${profile}"`,'small')}</div><div class="choice-grid">${model.eligible.map(g=>`<label><input type="checkbox" data-trend-key="${g.key}" data-profile="${profile}" ${config.keys===null||config.keys.includes(g.key)?'checked':''}> ${esc(g.a.name)} · ${g.a.date}<span class="help"> ${g.group.map(a=>esc(className(a.classId))).join('、')}</span></label>`).join('')||'<p class="help">暂无覆盖所选对象的小测。跨班比较请先关联场次。</p>'}</div></details>`;}
function profileChartPanel(sid){const config={...profileTrend(sid),metric:trendMode,from,to},model=T.trendData(data,config);return `<section class="panel"><div class="panel-head"><h2>小测成长曲线</h2>${btn('多学生 / 班级对比','analysis-open',`data-student="${sid}"`)}</div>${comparisonControls(config,true)}${comparisonChart(model)}${comparisonDetails(model)}</section>`;}
function analysisView(){const cfg=analysisState,model=T.trendData(data,cfg),choices=cfg.type==='student'?data.students:data.classes;return heading('成绩分析','按题型看表现，按关联小测看总成绩名次进步。',btn('返回小测列表','analysis-back')+btn('打印当前对比图','analysis-print','','primary'))+`<section class="panel"><div class="toolbar"><label>对比对象 <select data-trend="type">${option('student','学生对比',cfg.type)}${option('class','班级对比',cfg.type)}</select></label><label>开始日期 <input type="date" data-trend="from" value="${cfg.from}"></label><label>结束日期 <input type="date" data-trend="to" value="${cfg.to}"></label></div><details class="object-picker" open><summary>选择${cfg.type==='student'?'学生（可跨班）':'班级（最多两个）'} · 已选 ${cfg.ids.length}</summary><input id="analysis-object-search" type="search" value="${esc(cfg.objectQuery||'')}" placeholder="搜索姓名、学号或班级" aria-label="搜索对比对象"><div class="choice-grid object-options">${choices.map(s=>`<label data-object-label="${esc(cfg.type==='student'?className(s.classId)+' '+s.name+' '+s.number:s.name)}" ${(cfg.type==='student'?className(s.classId)+' '+s.name+' '+s.number:s.name).toLowerCase().includes((cfg.objectQuery||'').toLowerCase())?'':'hidden'}><input type="checkbox" data-trend-object="${s.id}" ${cfg.ids.includes(s.id)?'checked':''}> ${esc(cfg.type==='student'?className(s.classId)+' · '+s.name+' · '+(s.number||'无学号'):s.name)}</label>`).join('')}</div></details>${comparisonControls(cfg)}<div id="analysis-result">${comparisonChart(model)}${comparisonDetails(model)}</div></section>`;}
async function analysisAction(action,el){
  if(action==='sections'){sectionsDialog(data.activities.find(a=>a.id===el.dataset.id));return true;}
  if(action==='grade-ranking'){gradeDialog(el.dataset.id);return true;}
  if(action==='export-grade'){const a=data.activities.find(a=>a.id===el.dataset.id);workbook({'融合排名':gradeRows(a,gradeSelection.query,gradeSelection.cls).map(x=>({'年级名次':x.rank??'','班级':className(x.a.classId),'姓名':x.s.name,'学号':x.s.number,'总成绩':x.r.status==='score'?x.r.score:'','满分':x.a.total,'状态':x.r.status==='absent'?'缺考':states[x.r.status],'考试日期':x.a.date,'有效人数':quizInfo(a).gradeCount,'待录入人数':quizInfo(a).gradeBlank}))},`${a.name}-关联班级融合排名`);return true;}
  if(action==='analysis-open'){if(el.dataset.student){analysisState={...profileTrend(el.dataset.student),type:'student',ids:[el.dataset.student],from,to,objectQuery:''};}analysisOpen=true;view='quiz';close();render();return true;}
  if(action==='analysis-back'){analysisOpen=false;activityDetail=false;render();return true;}
  if(action==='trend-select-all'||action==='trend-select-none'){const profile=el.dataset.profile==='true',state=profile?profileTrend(studentId):analysisState;state.keys=action==='trend-select-all'?null:[];render();return true;}
  if(action==='analysis-print'){const model=T.trendData(data,analysisState);$('#print-root').innerHTML=`<article class="report"><header class="report-head"><h1>${esc(appName())} · 成绩对比</h1><p>${today()} · ${model.content==='total'?'总成绩':model.content}</p></header>${comparisonChart(model)}${comparisonDetails(model)}</article>`;$('#print-root').querySelectorAll('details').forEach(d=>d.open=true);window.print();return true;}
  return false;
}
async function analysisChange(el){
  if(el.dataset.sectionScore){const r=data.records.find(r=>r.id===el.dataset.record),a=data.activities.find(a=>a.id===r.activityId),name=el.dataset.sectionScore,n=el.value===''?null:Number(el.value);if(r.status==='absent'||n!==null&&(!Number.isFinite(n)||n<0||n>a.sections[name])){el.value=r.sectionScores?.[name]??'';throw Error(`分项成绩须为 0 至 ${a.sections[name]}，缺考不可录入`);}r.sectionScores={...r.sectionScores,[name]:n};await save();const opened=[...document.querySelectorAll('.section-details')].map(d=>d.open);render();document.querySelectorAll('.section-details').forEach((d,i)=>d.open=opened[i]);if($('#modal').open&&$('#modal [data-section-score]'))detail(r.id);return true;}
  if(el.id==='grade-class'){gradeSelection.cls=el.value;$('#grade-ranking').innerHTML=gradeRankingBody(data.activities.find(a=>a.id===gradeSelection.id));return true;}
  if(el.dataset.trend||el.dataset.trendKey||el.dataset.trendObject){const profile=el.dataset.profile==='true',state=profile?profileTrend(studentId):analysisState;
    if(el.dataset.trendObject){const ids=el.checked?[...state.ids,el.dataset.trendObject]:state.ids.filter(id=>id!==el.dataset.trendObject);if(state.type==='class'&&ids.length>2){el.checked=false;throw Error('班级对比最多选择两个班级');}state.ids=ids;state.keys=null;}
    else if(el.dataset.trendKey){const model=T.trendData(data,profile?{...state,from,to}:state),keys=state.keys===null?model.eligible.map(g=>g.key):state.keys;state.keys=el.checked?[...new Set([...keys,el.dataset.trendKey])]:keys.filter(k=>k!==el.dataset.trendKey);}
    else {const field=el.dataset.trend;if((field==='from'&&el.value&&state.to&&el.value>state.to)||(field==='to'&&el.value&&state.from&&el.value<state.from)){el.value=state[field];throw Error('开始日期不能晚于结束日期');}state[field]=el.type==='checkbox'?el.checked:el.value;if(field==='type'){state.ids=[];state.metric='rate';state.keys=null;state.objectQuery='';}if(profile&&field==='metric')trendMode=el.value;}
    render();return true;
  }return false;
}
document.addEventListener('input',e=>{const el=e.target;if(el.id==='analysis-object-search'){analysisState.objectQuery=el.value;const q=el.value.toLowerCase();document.querySelectorAll('[data-object-label]').forEach(x=>x.hidden=!x.dataset.objectLabel.toLowerCase().includes(q));}if(el.id==='grade-search'){gradeSelection.query=el.value;const cursor=el.selectionStart;$('#grade-ranking').innerHTML=gradeRankingBody(data.activities.find(a=>a.id===gradeSelection.id));$('#grade-search').focus();$('#grade-search').setSelectionRange(cursor,cursor);}});
function importUpdateSummary(item,row){if(!item)return '';const changes=[];if(Object.hasOwn(item,'status'))changes.push(item.status==='absent'?'总成绩 → 缺考':`总成绩 → ${item.score}`);for(const n of T.sectionNames)if(String(row?.[n]??'').trim())changes.push(`${n} → ${item.sectionScores?.[n]}`);return changes.length?changes.join('；')+'（其余保留）':'无非空成绩，保留原值';}
