'use strict';
const T=Tracker, $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={dict:'默写',quiz:'小测',hw:'重要作业'}, icons={overview:'◫',dict:'✎',quiz:'▥',hw:'▤',students:'♧',data:'⚙'};
const states={p:'p · 通过','p-':'p- · 临界',f:'f · 未通过',absent:'未参加',done:'完成',missing:'未完成',exempt:'免交',blank:'未录入',score:'已录入',pending:'待重默',failed:'已来未通过',passed:'已通过',correct:'订正正确',wrong:'订正不正确',none:'未订正'};
let data=T.empty(),db,revision=0,saved=true,saveQueue=Promise.resolve(),view='overview',classId='',selected={},search='',filter='',sort='name',studentId='',from='',to='',includeImages=false,reportKind='all',trendMode='rate',issueType='',importState=null;
const quizCache=new Map();
const quizInfo=a=>{if(!quizCache.has(a.id))quizCache.set(a.id,T.quizStats(data,a));return quizCache.get(a.id);};
const rankText=(rank,count)=>rank==null?'—':`${rank} / ${count} 人`;
const scoreMean=value=>value===null?'暂无数据':`${value.toFixed(2)} 分`;
const trendLabels={rate:'得分率',classRank:'班级名次',gradeRank:'年级名次'};
const trendOptions=()=>Object.entries(trendLabels).map(([v,label])=>option(v,label,trendMode)).join('');
const genderLabel=value=>({male:'男',female:'女',unknown:'未填写'}[value]||'未填写');
const appName=()=>data.settings?.appName||'紫笺';
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const nameOf=id=>data.students.find(s=>s.id===id)?.name||'未知学生',className=id=>data.classes.find(c=>c.id===id)?.name||'未知班级';
const pct=v=>v===null?'暂无数据':`${v.toFixed(1)}%`, diff=v=>v===null?'—':`${v>0?'+':''}${v.toFixed(1)} pp`;
const btn=(text,action,attrs='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const option=(v,text,current)=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(text)}</option>`;
const opts=(arr,current)=>arr.map(v=>option(v,states[v]||v,current)).join('');
const classOptions=(current,all=true)=>(all?option('','全部班级',current):'')+data.classes.map(c=>option(c.id,c.name,current)).join('');
const empty=(title,desc,button='')=>`<div class="empty"><div class="empty-icon">♧</div><h3>${title}</h3><p>${desc}</p>${button}</div>`;
const stat=(title,value,foot='',action='',attrs='')=>`<${action?'button':'div'} class="stat ${action?'alert':''}" ${action?`data-action="${action}" ${attrs}`:''}><span class="label">${title}</span><span class="value">${value}</span><span class="foot">${foot}</span></${action?'button':'div'}>`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function modal(title,body,wide=false){const m=$('#modal');m.className=wide?'wide':'';m.innerHTML=`<div class="dialog-head"><h2>${title}</h2>${btn('×','close','','ghost')}</div>${body}`;if(!m.open)m.showModal();}
const close=()=>$('#modal').close();
function request(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
async function openDB(){db=await new Promise((res,rej)=>{const r=indexedDB.open('zijian-student-tracker',1);r.onupgradeneeded=()=>{for(const n of ['classes','students','activities','records','images','meta'])r.result.createObjectStore(n,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);r.onblocked=()=>rej(Error('请关闭其他工作台页面后重试'));});
  const tx=db.transaction(['classes','students','activities','records','images','meta'],'readonly');
  const results=await Promise.all(['classes','students','activities','records','images','meta'].map(n=>request(tx.objectStore(n).getAll())));
  ['classes','students','activities','records','images'].forEach((n,i)=>data[n]=results[i]);revision=results[5].find(x=>x.id==='revision')?.value||0;data.settings=results[5].find(x=>x.id==='settings')?.value||{appName:'紫笺'};
  db.onversionchange=()=>db.close();
}
function save(){quizCache.clear();saved=false;updateSave('正在保存…');const snapshot=structuredClone(data);saveQueue=saveQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{
  const names=['classes','students','activities','records','images','meta'],tx=db.transaction(names,'readwrite');let conflict=false;
  const check=tx.objectStore('meta').get('revision');check.onsuccess=()=>{if((check.result?.value||0)!==revision){conflict=true;tx.abort();return;}
    for(const n of names.filter(n=>n!=='meta')){const st=tx.objectStore(n);st.clear();for(const item of snapshot[n])st.put(item);}
    tx.objectStore('meta').put({id:'revision',value:revision+1});
    tx.objectStore('meta').put({id:'settings',value:snapshot.settings||{appName:'紫笺'}});
  };tx.oncomplete=()=>{revision++;saved=true;updateSave('已自动保存');resolve();};tx.onabort=tx.onerror=()=>{saved=false;const e=Error(conflict?'另一个页面已修改数据，请先导出备份，再刷新此页面':'保存失败：空间不足或浏览器禁止存储，请立即导出完整备份');updateSave('保存失败 · 请备份',true);reject(e);};
}));return saveQueue;}
function updateSave(text,error=false){const el=$('#save-state');if(el){el.textContent=text;el.classList.toggle('error',error);}}
window.addEventListener('beforeunload',e=>{if(!saved){e.preventDefault();e.returnValue='';}});
function heading(title,subtitle,actions=''){return `<div class="heading"><div><div class="eyebrow">${esc(appName())} / STUDENT WORKSPACE</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="row">${actions}</div></div>`;}
function render(){quizCache.clear();document.title=`${appName()} · 学生跟踪工作台`;const names={overview:'工作台总览',...labels,students:'学生档案',data:'数据管理'};
  $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><button type="button" class="brand" data-action="rename-workspace" title="修改工作台名称" aria-label="修改工作台名称"><span class="brand-mark">✧</span><span class="brand-name">${esc(appName())}</span><span class="brand-edit" aria-hidden="true">✎</span></button><div class="brand-sub">每一份成长，都值得记录</div><nav class="nav">${Object.entries(names).map(([k,v])=>btn(`<span class="nav-icon">${icons[k]}</span>${v}`,'nav',`data-view="${k}"`,view===k?'active':'')).join('')}</nav><div class="side-bottom"><span class="local-dot"></span>本地工作台<div style="margin-top:9px">记录点滴，陪伴成长。<br>记得定期备份你的记录。</div></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">我的教学空间 / ${names[view]}</div><div class="topright"><span id="save-state" class="save ${saved?'':'error'}">${saved?'已自动保存':'有未保存的更改'}</span><select aria-label="全局班级" class="class-select" id="class-filter">${classOptions(classId)}</select><span class="badge">${today().replaceAll('-',' / ')}</span></div></header>${view==='overview'?overview():['dict','quiz','hw'].includes(view)?activityView():view==='students'?studentsView():dataView()}</main></div>`;
}
function overview(){const students=data.students.filter(s=>s.active&&(!classId||s.classId===classId)),issues=T.issues(data,classId),unique=xs=>new Set(xs.map(x=>x.r.studentId)).size;
  const acts=data.activities.filter(a=>!classId||a.classId===classId).sort(T.order).reverse();
  return heading('把成长，记录在日常里','默写、小测与作业，在这里有条不紊。',btn('＋ 新建记录','choose-activity','','primary'))+
  (!data.students.length?`<div class="welcome"><div><h2>欢迎来到你的教学工作台</h2><p>先导入一份学生名单，再开始记录每一次进步。</p><div class="steps"><span class="step"><b>1</b>建立班级名单</span><span class="step"><b>2</b>记录学习情况</span><span class="step"><b>3</b>查看成长报告</span></div><div style="margin-top:20px">${btn('导入学生名单','import-roster','','primary')} ${btn('手动添加学生','student-new')}</div></div><div class="welcome-flower">✳</div></div>`:'')+
  `<div class="stats">${stat('在读学生',students.length,`${classId?esc(className(classId)):data.classes.length+' 个班级'} · 共同成长`)}${stat('待重默',unique(issues.retake),'人 · 点击查看待跟进名单','issues','data-type="retake"')}${stat('订正待处理',unique(issues.correction),'人 · 点击查看对应场次','issues','data-type="correction"')}${stat('作业待补交',unique(issues.homework),'人 · 点击查看待补交名单','issues','data-type="homework"')}</div>
  <div class="grid2"><section class="panel"><div class="panel-head"><h2>最近的学习记录</h2><span class="count">共 ${acts.length} 场</span></div>${acts.length?acts.slice(0,7).map(a=>`<div class="list-item"><div class="list-icon">${icons[a.kind]}</div><div class="list-content"><div class="list-title">${esc(a.name)}</div><div class="list-desc">${esc(className(a.classId))} · ${a.date} · ${a.studentIds.length} 人</div></div><span class="badge">${labels[a.kind]}</span>${btn('查看 →','open-activity',`data-id="${a.id}"`,'ghost small')}</div>`).join(''):empty('还没有学习记录','从一次默写、一场小测或一份作业开始。')}</section>
  <section class="panel"><h2>快捷记录</h2>${Object.entries(labels).map(([k,v])=>`<div class="list-item"><div class="list-icon">${icons[k]}</div><div class="list-content"><div class="list-title">${v}</div><div class="list-desc">${k==='dict'?'默认通过，快速标记需要关注的同学':k==='quiz'?'不同总分，也能看见真实的进步':'完成、补交与作业照片，一起留存'}</div></div>${btn('＋','activity-new',`data-kind="${k}"`,'small')}</div>`).join('')}<div class="divider"></div><p class="help">小提醒<br>数据保存在当前浏览器中。更换设备前，请在「数据管理」导出完整备份，图片也会一起保留。</p>${btn('备份我的数据','backup','','small')}</section></div>`;
}
function currentActivity(){let acts=data.activities.filter(a=>a.kind===view&&(!classId||a.classId===classId)).sort(T.order).reverse();return acts.find(a=>a.id===selected[view])||acts[0];}
function recordRows(a){if(!a)return[];const prev=T.previous(data,a);let rows=data.records.filter(r=>r.activityId===a.id).map(r=>({r,s:data.students.find(s=>s.id===r.studentId),prior:prev?T.record(data,prev.id,r.studentId):null}));
  rows=rows.filter(({r,s,prior})=>{if(search&&!`${s.name} ${s.number}`.toLowerCase().includes(search.toLowerCase()))return false;
    if(!filter)return true;
    if(filter==='retake')return r.status==='f'&&r.retake==='pending';
    if(filter==='failed')return r.status==='f'&&r.retake==='failed';
    if(filter==='correction')return prior&&prior.status!=='absent'&&prior.correction!=='correct';
    if(filter==='own-correction')return r.status!=='absent'&&r.correction!=='correct';
    if(filter==='unsubmitted')return r.status==='missing'&&!r.submitted;
    if(filter==='submitted')return r.status==='missing'&&r.submitted;
    if(['good','improve'].includes(filter))return data.images.some(i=>i.recordId===r.id&&i.tag===filter);
    return r.status===filter;
  });
  return rows.sort((x,y)=>{const sign=sort.endsWith('-asc')?1:-1;
    if(sort.startsWith('score')||sort.startsWith('rate'))return sign*((x.r.score??-Infinity)-(y.r.score??-Infinity))||x.s.name.localeCompare(y.s.name,'zh');
    if(sort.startsWith('delta'))return sign*((T.delta(data,a,x.r)??-Infinity)-(T.delta(data,a,y.r)??-Infinity))||x.s.name.localeCompare(y.s.name,'zh');
    if(sort==='class-rank'||sort==='grade-rank'){const ranks=sort==='class-rank'?quizInfo(a).classRanks:quizInfo(a).gradeRanks;return (ranks.get(x.s.id)??Infinity)-(ranks.get(y.s.id)??Infinity)||x.s.name.localeCompare(y.s.name,'zh');}
    if(sort==='pass')return (T.summary(data,y.s.id).dict??-1)-(T.summary(data,x.s.id).dict??-1);
    if(sort==='status')return x.r.status.localeCompare(y.r.status)||x.s.name.localeCompare(y.s.name,'zh');
    return String(x.s[sort==='number'?'number':'name']).localeCompare(String(y.s[sort==='number'?'number':'name']),'zh',{numeric:true});
  });
}
function activityView(){const a=currentActivity(),acts=data.activities.filter(a=>a.kind===view&&(!classId||a.classId===classId)).sort(T.order).reverse();
  let html=heading(labels[view],view==='dict'?'默认 p，只标记例外；重默与订正，逐项跟进。':view==='quiz'?'用得分率连接每一次小测，看见进步的轨迹。':'从按时完成到及时补交，留住每一份用心。',btn(`＋ 新建${labels[view]}`,'activity-new',`data-kind="${view}"`,'primary'));
  if(!a)return html+`<section class="panel">${empty(`还没有${labels[view]}记录`,'创建一场记录后，该班在读学生会自动加入。',btn('开始记录','activity-new',`data-kind="${view}"`,'primary'))}</section>`;
  selected[view]=a.id;const prev=view==='dict'?T.previous(data,a):null,rows=recordRows(a);
  const filters=view==='dict'?[['','全部状态'],['p','p · 通过'],['p-','p- · 临界'],['f','f · 未通过'],['retake','待重默'],['failed','重默未通过'],['correction','上次订正有问题'],['own-correction','本次订正有问题'],['absent','未参加']]:view==='quiz'?[['','全部状态'],['score','已录入'],['blank','未录入'],['absent','缺考']]:[['','全部状态'],['done','按时完成'],['unsubmitted','仍未补交'],['submitted','已补交'],['exempt','免交'],['good','优秀作业图片'],['improve','需改进图片']];
  html+=`<section class="panel"><div class="toolbar"><select id="activity-select" aria-label="选择活动" class="grow">${acts.map(x=>option(x.id,`${x.date} · ${x.name} · ${className(x.classId)}`,a.id)).join('')}</select>${view==='quiz'?btn('导入成绩','import-scores')+btn('成绩模板','score-template')+btn('跨班关联','quiz-link',`data-id="${a.id}"`):''}${btn('导出 Excel','export-module')}${btn('删除本场','delete-activity',`data-id="${a.id}"`,'ghost danger')}</div><div class="row spread"><div><strong>${esc(a.name)}</strong> <span class="badge">${esc(className(a.classId))}</span> <span class="help">${a.date} · ${a.studentIds.length} 人${view==='quiz'?` · 总分 ${a.total}`:''}</span></div><span class="count">显示 ${rows.length} / ${a.studentIds.length} 人</span></div>
  ${view==='dict'?`<p class="help">加权通过率：p = 1，p- = 0.5，f = 0；未参加不计入。只有 f 需要重默。<br>上次订正对应：${prev?`<strong>${esc(prev.name)} · ${prev.date}</strong>（修改会保存至该场次）`:'暂无上一场默写'}；本次订正也可通过每行「详情」登记。</p>`:view==='quiz'?'<p class="help">趋势与进步幅度按得分率计算；pp 为百分点。空白不计入，缺考请单独标记。</p>':'<p class="help">补交后保留原始未完成状态；免交不计入完成率。</p>'}
  ${view==='quiz'?quizStatisticsPanel(a):''}<div class="toolbar"><input id="record-search" type="search" placeholder="搜索姓名或学号…" value="${esc(search)}"><select id="record-filter" aria-label="状态筛选">${filters.map(([v,t])=>option(v,t,filter)).join('')}</select><select id="record-sort" aria-label="排序">${[['name','姓名排序'],['number','学号排序'],['status','状态排序'],...(view==='quiz'?[['score-desc','成绩从高到低'],['score-asc','成绩从低到高'],['rate-desc','得分率从高到低'],['class-rank','班级名次从前到后'],['grade-rank','年级名次从前到后'],['delta-desc','进步幅度从高到低']]:view==='dict'?[['pass','累计通过率从高到低']]:[])].map(([v,t])=>option(v,t,sort)).join('')}</select></div>
  <div class="table-wrap"><table><thead><tr><th>学生</th>${view==='dict'?'<th>首次默写</th><th>重默跟进</th><th>上次订正</th><th>累计通过率</th>':view==='quiz'?'<th>成绩</th><th>状态</th><th>得分率</th><th>较上次</th><th>班级名次</th><th>年级名次</th>':'<th>原始完成情况</th><th>补交跟进</th><th>作业图片</th>'}<th>个人备注</th><th>操作</th></tr></thead><tbody>${rows.map(x=>activityRow(a,x)).join('')||'<tr><td colspan="10" class="empty">没有符合筛选条件的学生</td></tr>'}</tbody></table></div></section>`;return html;
}
function selectField(r,field,values,current=r[field],disabled=false){return `<select aria-label="${esc(nameOf(r.studentId))} ${field}" data-record="${r.id}" data-field="${field}" ${disabled?'disabled':''}>${values.map(v=>option(v,v==='absent'&&data.activities.find(a=>a.id===r.activityId)?.kind==='quiz'?'缺考':states[v]||v,current)).join('')}</select>`;}
function dateField(r,field){return `<input class="inline-date" type="date" aria-label="${field==='retakeDate'?'重默日期':'补交日期'}" data-record="${r.id}" data-field="${field}" value="${esc(r[field])}">`;}
function activityRow(a,{r,s,prior}){let cols='';
  if(a.kind==='dict')cols=`<td><div class="segments">${['p','p-','f','absent'].map(v=>btn(v==='absent'?'未参加':v,'dict-status',`data-id="${r.id}" data-value="${v}"`,v===r.status?'on':'')).join('')}</div></td><td>${r.status==='f'?selectField(r,'retake',['pending','failed','passed'])+(r.retake!=='pending'?dateField(r,'retakeDate'):''):'<span class="muted">无需重默</span>'}</td><td>${prior&&prior.status!=='absent'?selectField(prior,'correction',['correct','none','wrong']):'<span class="muted">不适用</span>'}</td><td><span class="badge">${pct(T.summary(data,s.id).dict)}</span></td>`;
  if(a.kind==='quiz')cols=`<td><input type="number" min="0" max="${a.total}" step="any" aria-label="${esc(s.name)} 成绩" placeholder="—" data-record="${r.id}" data-field="score" value="${r.score??''}" ${r.status==='absent'?'disabled':''}> <span class="count">/ ${a.total}</span></td><td>${selectField(r,'status',['blank','score','absent'])}</td><td>${r.status==='score'?pct(r.score/a.total*100):'—'}</td><td>${diff(T.delta(data,a,r))}</td><td>${rankText(quizInfo(a).classRanks.get(s.id),quizInfo(a).classCount)}</td><td>${rankText(quizInfo(a).gradeRanks.get(s.id),quizInfo(a).gradeCount)}</td>`;
  if(a.kind==='hw'){const images=data.images.filter(i=>i.recordId===r.id);cols=`<td>${selectField(r,'status',['done','missing','exempt'])}</td><td>${r.status==='missing'?`<label><input type="checkbox" data-record="${r.id}" data-field="submitted" ${r.submitted?'checked':''}> 已补交</label>${r.submitted?dateField(r,'submitDate'):''}`:'<span class="muted">无需补交</span>'}</td><td><div class="thumbs">${images.slice(0,2).map(i=>`<img class="thumb" src="${i.data}" alt="${esc(i.name)}" data-action="image-view" data-id="${i.id}">`).join('')}${btn(images.length?`${images.length} 张 · 管理`:'＋ 图片','photos',`data-id="${r.id}"`,'small')}</div></td>`;}
  return `<tr><td><button class="link student-name" data-action="profile" data-id="${s.id}">${esc(s.name)}</button><div class="student-no">${esc(s.number)||'无学号'}${s.active?'':' · 已停用'}</div></td>${cols}<td><input class="note" aria-label="${esc(s.name)} 备注" data-record="${r.id}" data-field="note" placeholder="添加备注…" value="${esc(r.note)}"></td><td>${btn('详情','record-detail',`data-id="${r.id}"`,'ghost small')}</td></tr>`;
}
function quizStatisticsPanel(a){const q=quizInfo(a);return `<div class="stats quiz-stats">${stat('班级平均分',scoreMean(q.classAverage),`${q.classCount} 人有效 · ${q.classBlank} 人待录入 · ${q.classAbsent} 人缺考`)}${stat('年级平均分',scoreMean(q.gradeAverage),`${q.group.length} 个关联班级 · ${q.gradeCount} 人有效`)}${stat('班级男生平均分',scoreMean(q.maleAverage),`${q.maleCount} 人有效成绩`)}${stat('班级女生平均分',scoreMean(q.femaleAverage),`${q.femaleCount} 人有效成绩`)}</div><p class="help quiz-scope">年级范围：${q.group.map(x=>esc(className(x.classId))).join('、')}（仅同一场关联小测，满分 ${a.total}）。${q.group.length===1?'目前仅包含本班，可通过「跨班关联」加入其他班级。':''}<br>按有效成绩人数加权计算平均分；同分并列名次（1、2、2、4）。${q.unknownCount} 位有效成绩学生未填写性别，不计入男、女生分组。${q.gradeBlank?`还有 ${q.gradeBlank} 人未录入，均分和名次暂定。`:''}表格筛选不改变统计范围。</p>`;}
function chart(qs,mode=trendMode){if(!qs.length)return empty('暂无小测趋势','录入成绩后，这里会出现小测趋势图。');
  const points=qs.map(q=>{const info=quizInfo(q.a),rank=mode==='classRank'?info.classRanks.get(q.r.studentId):info.gradeRanks.get(q.r.studentId);return {...q,plot:mode==='rate'?q.value:rank,count:mode==='classRank'?info.classCount:info.gradeCount,info};});
  const ranked=mode!=='rate',w=760,h=250,pad=55,max=ranked?Math.max(1,...points.map(p=>p.count)):100;
  const x=i=>qs.length===1?w/2:pad+i*(w-pad*2)/(qs.length-1),y=v=>ranked?28+(v-1)/Math.max(1,max-1)*(h-80):h-52-v/100*(h-80),labelEvery=Math.max(1,Math.ceil(qs.length/7));
  const ticks=ranked?[...new Set([1,...[.25,.5,.75,1].map(f=>Math.round(1+(max-1)*f))])]:[0,25,50,75,100];
  return `<svg class="chart" data-metric="${mode}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${trendLabels[mode]}趋势，${ranked?'第 1 名在最上方':'纵轴 0 至 100 百分比'}"><title>历次小测${trendLabels[mode]}</title>${ticks.map(v=>`<line class="grid" x1="${pad}" x2="${w-pad}" y1="${y(v)}" y2="${y(v)}"/><text x="2" y="${y(v)+4}">${ranked?'第 '+v+' 名':v+'%'}</text>`).join('')}<polyline class="line" points="${points.map((q,i)=>`${x(i)},${y(q.plot)}`).join(' ')}"/>${points.map((q,i)=>`<circle class="dot" tabindex="0" cx="${x(i)}" cy="${y(q.plot)}" r="4"><title>${esc(q.a.name)} · ${q.a.date}：${q.r.score}/${q.a.total}（${pct(q.value)}）；班级 ${rankText(q.info.classRanks.get(q.r.studentId),q.info.classCount)}；年级 ${rankText(q.info.gradeRanks.get(q.r.studentId),q.info.gradeCount)}，${q.info.group.length} 个关联班级${q.info.gradeBlank?'，成绩尚未录齐，名次暂定':''}</title></circle>${points.length<=12?`<text x="${x(i)}" y="${y(q.plot)-11}" text-anchor="middle">${ranked?q.plot+' / '+q.count:pct(q.plot)}</text>`:''}${i%labelEvery===0||i===points.length-1?`<text x="${x(i)}" y="${h-27}" text-anchor="middle">${q.a.date.slice(5)}</text><text x="${x(i)}" y="${h-10}" text-anchor="middle">${esc(q.a.name.length>9?q.a.name.slice(0,8)+'…':q.a.name)}</text>`:''}`).join('')}</svg>`;
}
function trendHelp(mode=trendMode){return mode==='rate'?'得分率 = 得分 ÷ 当次总分，适合比较不同总分的小测；试卷难度不同也会影响得分率。':'第 1 名在最上方，向上表示名次进步；图上标注「名次 / 有效成绩人数」。人数变化会影响名次的可比性。年级只统计同一场关联小测。';}
function studentsView(){const students=data.students.filter(s=>(!classId||s.classId===classId)&&(!search||`${s.name} ${s.number}`.includes(search))).sort((a,b)=>a.name.localeCompare(b.name,'zh'));
  let html=heading('每个学生，都有自己的轨迹','把学习记录连起来，看见细微而具体的成长。',btn('＋ 添加学生','student-new','','primary'));
  if(studentId){const s=data.students.find(x=>x.id===studentId);if(!s){studentId='';return studentsView();}const sum=T.summary(data,s.id,from,to);
    html+=`<div class="toolbar">${btn('← 返回学生列表','student-back')}<span class="spacer"></span><span class="range-label">日期范围</span><input aria-label="开始日期" type="date" id="date-from" value="${from}"><span class="muted">至</span><input aria-label="结束日期" type="date" id="date-to" value="${to}">${btn('清除范围','range-clear','','small')}${btn('导出 Excel','export-student')}${btn('打印 / PDF 报告','report','','primary')}</div>
    <div class="profile-banner row"><div class="avatar">${esc(s.name.slice(0,1))}</div><div><strong style="font-size:21px">${esc(s.name)}</strong><div class="help">${esc(className(s.classId))} · 学号 ${esc(s.number)||'未填写'} · ${genderLabel(s.gender)} · ${s.active?'在读':'已停用'}</div></div><span class="spacer"></span>${btn('编辑资料','student-edit',`data-id="${s.id}"`)}</div><div class="stats">${stat('加权默写通过率',pct(sum.dict),`${sum.dictCount} 次有效默写`)}${stat('最近小测得分率',sum.quizzes.length?pct(sum.quizzes.at(-1).value):'暂无数据',`${sum.quizzes.length} 次有效小测`)}${stat('作业完成率',pct(sum.hw),'包含已补交 · 免交不计')}${stat('初次未完成 / 已补交',`${sum.missing} / ${sum.submitted}`,'次 · 保留原始记录')}</div><section class="panel"><div class="panel-head"><h2>小测成长曲线</h2><select id="trend-mode" aria-label="趋势指标">${trendOptions()}</select></div><p class="help">${trendHelp()} 缺考和未录入的场次不绘制数据点。</p>${chart(sum.quizzes)}</section>${studentTables(s.id,false,true)}`;return html;
  }
  return html+`<section class="panel"><div class="toolbar"><input type="search" id="student-search" placeholder="搜索姓名或学号…" value="${esc(search)}">${btn('导入名单','import-roster')}${btn('名单模板','roster-template')}<span class="count">${students.length} 位学生</span></div>${students.length?`<div class="table-wrap"><table><thead><tr><th>学生</th><th>班级</th><th>性别</th><th>状态</th><th>默写通过率</th><th>最近小测</th><th>作业完成率</th><th>操作</th></tr></thead><tbody>${students.map(s=>{const sum=T.summary(data,s.id);return `<tr><td><button class="link student-name" data-action="profile" data-id="${s.id}">${esc(s.name)}</button><div class="student-no">${esc(s.number)||'无学号'}</div></td><td>${esc(className(s.classId))}</td><td>${genderLabel(s.gender)}</td><td><span class="badge ${s.active?'green':''}">${s.active?'在读':'已停用'}</span></td><td>${pct(sum.dict)}</td><td>${sum.quizzes.length?pct(sum.quizzes.at(-1).value):'—'}</td><td>${pct(sum.hw)}</td><td>${btn('编辑','student-edit',`data-id="${s.id}"`,'small')}${btn('查看档案 →','profile',`data-id="${s.id}"`,'ghost small')}</td></tr>`;}).join('')}</tbody></table></div>`:empty('从一份名单开始','导入 Excel 名单，或手动添加第一位学生。',btn('导入学生名单','import-roster','','primary'))}</section>`;
}
function studentTables(sid,report=false,photos=false,selection='all'){return exportKinds(selection).map(([kind,label])=>{const es=T.entries(data,sid,kind,from,to);return `<section class="${report?'':'panel'}"><h2>${label}记录 <span class="count">${es.length} 次</span></h2>${es.length?`<${report?'div':'div class="table-wrap"'}><table><thead><tr><th>日期 / 名称</th>${kind==='dict'?'<th>首次结果</th><th>重默</th><th>本次订正</th>':kind==='quiz'?'<th>成绩 / 总分</th><th>得分率</th><th>较上次</th><th>班级 / 年级名次</th>':'<th>原始状态</th><th>补交情况</th>'}<th>备注</th>${report?'':'<th>操作</th>'}</tr></thead><tbody>${es.map(({a,r})=>`<tr><td>${a.date}<br>${esc(a.name)}</td>${kind==='dict'?`<td>${states[r.status]}</td><td>${r.status==='f'?states[r.retake]+(r.retakeDate?'<br>'+r.retakeDate:''):'无需重默'}</td><td>${r.status==='absent'?'不适用':states[r.correction]}</td>`:kind==='quiz'?`<td>${r.status==='score'?`${r.score} / ${a.total}`:r.status==='absent'?'缺考':'未录入'}</td><td>${r.status==='score'?pct(r.score/a.total*100):'—'}</td><td>${diff(T.delta(data,a,r))}</td><td>班 ${rankText(quizInfo(a).classRanks.get(r.studentId),quizInfo(a).classCount)}<br>年 ${rankText(quizInfo(a).gradeRanks.get(r.studentId),quizInfo(a).gradeCount)}</td>`:`<td>${states[r.status]}</td><td>${r.status==='missing'?(r.submitted?'已补交 '+r.submitDate:'未补交'):'不适用'}</td>`}<td class="detail-note">${esc(r.note)||'—'}</td>${report?'':`<td>${btn('详情','record-detail',`data-id="${r.id}"`,'small')}</td>`}</tr>`).join('')}</tbody></table></div>`:'<p class="help">此日期范围内暂无记录</p>'}${kind==='hw'&&photos?homeworkPhotos(es,report):''}</section>`;}).join('');}
function homeworkPhotos(es,report){const groups=es.map(({a,r})=>({a,images:data.images.filter(i=>i.recordId===r.id)})).filter(x=>x.images.length);return groups.map(({a,images})=>`<p class="help">${a.date} · ${esc(a.name)}</p><div class="${report?'report-images':'thumbs'}">${images.map(i=>report?`<figure><img src="${i.data}" alt="${esc(i.name)}"><figcaption>${i.tag==='good'?'优秀作业':'需改进'} · ${esc(i.name)}</figcaption></figure>`:`<img class="thumb" src="${i.data}" alt="${esc(i.name)}" data-action="image-view" data-id="${i.id}">`).join('')}</div>`).join('');}
function dataView(){return heading('让每一份记录，都妥善留存','管理班级、导入名单，定期备份你的教学资料。')+`<section class="panel"><div class="panel-head"><div><h2>工作台名称</h2><p class="help">${esc(appName())} · 可自定义左上角名称、页面标题和报告署名。</p></div>${btn('修改名称','rename-workspace')}</div></section><div class="grid2"><section class="panel"><div class="panel-head"><h2>班级管理</h2>${btn('＋ 新建班级','class-new','','small')}</div>${data.classes.length?data.classes.map(c=>`<div class="list-item"><div class="list-icon">♧</div><div class="list-content"><div class="list-title">${esc(c.name)}</div><div class="list-desc">${data.students.filter(s=>s.classId===c.id&&s.active).length} 位在读学生 · ${data.activities.filter(a=>a.classId===c.id).length} 场记录</div></div>${btn('重命名','class-edit',`data-id="${c.id}"`,'small')}</div>`).join(''):empty('还没有班级','导入名单会自动创建对应班级。')}<div class="divider"></div><div class="row">${btn('导入学生名单','import-roster','','primary')}${btn('下载名单模板','roster-template')}${btn('导出学生名单','export-roster')}</div><p class="help">模板包含班级、姓名、学号、性别（男 / 女 / 未填写）。学号建议以文本格式填写，保留前导零。</p></section>
  <section class="panel"><h2>完整备份与恢复</h2><p class="help">当前共有 ${data.students.length} 位学生、${data.activities.length} 场活动、${data.images.length} 张图片。<br>完整备份会保存全部数据和图片，适合迁移与长期存档。</p><div class="row">${btn('↓ 导出完整备份','backup','','primary')}${btn('恢复备份','restore')}</div><div class="divider"></div><h2>导出学习记录</h2><p class="help">Excel 工作簿按默写、小测和作业分表，包含明细和备注。作业图片需通过完整备份或学生 PDF 报告保存。</p>${btn('选择内容并导出 Excel','export-all')}</section></div><section class="panel"><h2>使用小贴士</h2><p class="help">① 使用同一个浏览器、同一地址打开工作台，记录会自动保留。清除浏览器网站数据会删除本地记录。<br>② 更换设备或浏览器前，先导出完整备份，再到新环境中恢复。<br>③ 推荐每周备份一次。不要在多个页面同时编辑同一份数据。<br>④ 学生停用后保留历史记录，新建活动不再加入该学生；之后新增的学生不会被自动加入旧活动。<br>⑤ PDF 报告使用浏览器的打印功能，请在打印窗口选择“另存为 PDF”，纸张 A4。</p></section>`;}
function chooseActivity(){modal('今天想记录什么？',`<div class="row">${Object.entries(labels).map(([k,v])=>btn(`${icons[k]} 新建${v}`,'activity-new',`data-kind="${k}"`,'primary')).join('')}</div>`);}
function activityForm(kind){if(!data.students.some(s=>s.active)){toast('请先添加或导入学生名单');studentForm();return;}modal(`新建${labels[kind]}`,`<form id="activity-form" data-kind="${kind}"><div class="form-grid"><label class="field"><span>班级</span><select name="classId" required>${classOptions(classId||data.classes[0]?.id,false)}</select></label><label class="field"><span>日期</span><input name="date" type="date" value="${today()}" required></label><label class="field full"><span>名称</span><input name="name" placeholder="例如：Unit 1 词汇默写" maxlength="120" required></label>${kind==='quiz'?`<label class="field"><span>本次总分</span><input name="total" type="number" min="0.01" step="any" value="100" required></label><label class="field full"><span>同一场跨班小测</span><select name="joinQuizId" id="new-quiz-group">${quizJoinOptions()}</select></label>`:''}</div><p class="help">自动加入所选班级当前在读学生。${kind==='dict'?'首次结果默认 p，订正默认正确。':kind==='hw'?'完成情况默认完成。':'其他班级考同一份试卷时，选择加入已有小测。总分保持一致；班级实际考试日期可不同。缺考不按零分计入。'}</p><div class="dialog-actions">${btn('取消','close')}<button class="primary">创建记录</button></div></form>`);}
function quizJoinOptions(currentActivity=null){const seen=new Set(),groups=data.activities.filter(a=>a.kind==='quiz').sort(T.order).reverse().filter(a=>{const key=T.quizKey(a);if(seen.has(key)||currentActivity&&key===T.quizKey(currentActivity))return false;seen.add(key);return true;});return option('',currentActivity?'本班单独统计（解除与其他班级的关联）':'新建一场小测（不与现有场次合并）','')+groups.map(a=>option(a.id,`${a.name} · ${a.date} · 满分 ${a.total} · ${T.quizGroup(data,a).map(x=>className(x.classId)).join('、')}`,'')).join('');}
function quizLinkDialog(id){const a=data.activities.find(a=>a.id===id),group=T.quizGroup(data,a);modal('关联同一场跨班小测',`<form id="quiz-link-form" data-id="${id}"><p class="help">当前：${esc(a.name)} · 满分 ${a.total}<br>已关联：${group.map(x=>esc(className(x.classId))).join('、')}。只会调整当前班级这场记录的归属，不修改成绩。</p><label class="field"><span>年级统计归属</span><select name="targetId"><option value="keep">保留当前关联</option>${quizJoinOptions(a)}</select></label><p class="help">请选择同一份试卷对应的小测。总分不同、班级重复或学生重复时无法关联；旧记录不会仅因同名自动合并。</p><div class="dialog-actions">${btn('取消','close')}<button class="primary">保存关联</button></div></form>`);}
function studentForm(id){const s=data.students.find(s=>s.id===id);modal(s?'编辑学生资料':'添加学生',`<form id="student-form" data-id="${id||''}"><div class="form-grid"><label class="field"><span>姓名</span><input name="name" value="${esc(s?.name)}" required maxlength="80"></label><label class="field"><span>学号（可选）</span><input name="number" value="${esc(s?.number)}" maxlength="80"></label><label class="field"><span>班级${s?'（历史记录保留原班级）':''}</span><select name="classId">${classOptions(s?.classId||classId||data.classes[0]?.id,false)}</select></label>${s?'':`<label class="field"><span>或新建班级</span><input name="newClass" placeholder="例如：七年级 1 班" ${!data.classes.length?'required':''} maxlength="80"></label>`}<label class="field"><span>性别（可选）</span><select name="gender">${['unknown','male','female'].map(v=>option(v,genderLabel(v),s?.gender||'unknown')).join('')}</select></label><label class="field"><span>状态</span><select name="active">${option('true','在读',s?.active===false?'false':'true')}${option('false','停用',s?.active===false?'false':'true')}</select></label></div><p class="help">同班学号须唯一。同名学生请分别填写学号，方便成绩导入匹配。</p><div class="dialog-actions">${btn('取消','close')}<button class="primary">保存学生</button></div></form>`);}
function workspaceNameForm(){modal('修改工作台名称',`<form id="workspace-name-form"><label class="field"><span>工作台名称</span><input name="appName" required maxlength="20" value="${esc(appName())}" placeholder="例如：Sophia 的教学工作台"></label><p class="help">支持 1–20 个字符。保存后更新左上角名称、页面标题和报告署名，并随完整备份保存。</p><div class="dialog-actions">${btn('取消','close')}<button class="primary">保存名称</button></div></form>`);}
function classForm(id){const c=data.classes.find(c=>c.id===id);modal(c?'重命名班级':'新建班级',`<form id="class-form" data-id="${id||''}"><label class="field"><span>班级名称</span><input name="name" required maxlength="80" value="${esc(c?.name)}"></label><div class="dialog-actions"><button class="primary">保存</button></div></form>`);}
function detail(id){const r=data.records.find(x=>x.id===id),a=data.activities.find(x=>x.id===r.activityId);modal(`${esc(nameOf(r.studentId))} · ${esc(a.name)}`,`<p class="help">${a.date} · ${esc(className(a.classId))} · ${labels[a.kind]}</p>${a.kind==='dict'?`<div class="field"><span>本次默写的订正情况</span>${selectField(r,'correction',['correct','none','wrong'],r.correction,r.status==='absent')}</div><p class="help">这里修改的是「${esc(a.name)}」的订正，下次默写的“上次订正”栏会同步显示。</p>`:''}<label class="field"><span>个人备注</span><textarea data-record="${r.id}" data-field="note">${esc(r.note)}</textarea></label><div class="row">${a.kind==='hw'?btn('管理作业图片','photos',`data-id="${r.id}"`):''}${btn('打开对应场次','open-activity',`data-id="${a.id}"`)}${btn('完成','close','','primary')}</div>`);}
function photos(id){const r=data.records.find(x=>x.id===id),imgs=data.images.filter(x=>x.recordId===id);modal(`${esc(nameOf(r.studentId))} · 作业图片`,`<label class="file-label">＋ 上传图片<input type="file" id="photo-upload" data-record="${id}" accept="image/jpeg,image/png,image/webp" multiple></label><p class="help">支持 JPG、PNG、WebP，每张最大 20 MB。自动缩至最长边 1600 像素；点击图片可放大。</p><div class="row">${imgs.map(i=>`<div class="photo-card"><img src="${i.data}" alt="${esc(i.name)}" data-action="image-view" data-id="${i.id}"><select data-image="${i.id}" aria-label="图片标签">${option('good','优秀作业',i.tag)}${option('improve','需改进',i.tag)}</select>${btn('删除图片','image-delete',`data-id="${i.id}" data-record="${id}"`,'small ghost danger')}</div>`).join('')||'<p class="help">还没有上传图片</p>'}</div><div class="dialog-actions">${btn('完成','close','','primary')}</div>`);}
async function compressImage(file){if(file.size>20*1024*1024)throw Error(`${file.name} 超过 20 MB`);if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('仅支持 JPG、PNG、WebP 图片');const url=URL.createObjectURL(file);try{const im=new Image();im.src=url;await im.decode();const scale=Math.min(1,1600/Math.max(im.width,im.height)),can=document.createElement('canvas');can.width=Math.round(im.width*scale);can.height=Math.round(im.height*scale);const ctx=can.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,can.width,can.height);ctx.drawImage(im,0,0,can.width,can.height);return can.toDataURL('image/jpeg',.82);}finally{URL.revokeObjectURL(url);}}
function showIssues(type){issueType=type;const title={retake:'待重默名单',correction:'订正待处理名单',homework:'作业待补交名单'},xs=T.issues(data,classId)[type];modal(title[type],`<p class="help">${classId?esc(className(classId)):'全部班级'} · ${new Set(xs.map(x=>x.r.studentId)).size} 人 · ${xs.length} 条记录</p><div class="table-wrap"><table><thead><tr><th>学生 / 班级</th><th>日期 / 场次</th><th>待处理事项</th><th>操作</th></tr></thead><tbody>${xs.map(({a,r})=>`<tr><td>${esc(nameOf(r.studentId))}<br><span class="help">${esc(className(a.classId))}</span></td><td>${a.date}<br>${esc(a.name)}</td><td>${type==='retake'?states[r.retake]:type==='correction'?states[r.correction]:'仍未补交'}</td><td>${btn('去处理','open-issue',`data-id="${a.id}" data-type="${type}" data-student="${r.studentId}"`,'small')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">全部处理完啦，暂无待跟进记录。</td></tr>'}</tbody></table></div>`,true);}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function workbook(sheets,name){if(!globalThis.XLSX)throw Error('Excel 库未加载，请确认 vendor 文件夹与网页放在一起');const wb=XLSX.utils.book_new();for(const [title,rows]of Object.entries(sheets)){const ws=XLSX.utils.json_to_sheet(rows);const keys=Object.keys(rows[0]||{});ws['!cols']=keys.map(k=>({wch:k.includes('备注')?35:k.includes('名称')?24:k.includes('日期')?14:18}));ws['!autofilter']={ref:ws['!ref']||'A1'};XLSX.utils.book_append_sheet(wb,ws,title.slice(0,31));}XLSX.writeFile(wb,name.replace(/[\\/:*?"<>|]/g,'_')+'.xlsx');}
function exportRows(kind,records){return records.map(r=>{const a=data.activities.find(a=>a.id===r.activityId),s=data.students.find(s=>s.id===r.studentId);const row={'班级':className(a.classId),'姓名':s.name,'学号':s.number,'性别':genderLabel(s.gender),'日期':a.date,'名称':a.name};
  if(kind==='dict')Object.assign(row,{'首次结果':states[r.status],'重默情况':r.status==='f'?states[r.retake]:'无需重默','重默日期':r.status==='f'?r.retakeDate:'','本次订正':r.status==='absent'?'不适用':states[r.correction],'累计加权通过率(%)':T.summary(data,s.id).dict});
  if(kind==='quiz'){const info=quizInfo(a);Object.assign(row,{'得分':r.status==='score'?r.score:'','总分':a.total,'状态':r.status==='absent'?'缺考':states[r.status],'得分率(%)':r.status==='score'?Number((r.score/a.total*100).toFixed(2)):'','较上次(百分点)':T.delta(data,a,r)===null?'':Number(T.delta(data,a,r).toFixed(2)),'班级名次':info.classRanks.get(r.studentId)??'','班级有效成绩人数':info.classCount,'年级名次':info.gradeRanks.get(r.studentId)??'','年级有效成绩人数':info.gradeCount,'班级平均分':info.classAverage,'年级平均分':info.gradeAverage,'班级男生平均分':info.maleAverage,'班级女生平均分':info.femaleAverage,'班级男生有效人数':info.maleCount,'班级女生有效人数':info.femaleCount,'性别未填写有效人数':info.unknownCount,'年级关联班级':info.group.map(x=>className(x.classId)).join('、'),'年级待录入人数':info.gradeBlank,'跨班小测编号':T.quizKey(a)});}
  if(kind==='hw')Object.assign(row,{'原始完成情况':states[r.status],'是否补交':r.status==='missing'?(r.submitted?'是':'否'):'不适用','补交日期':r.status==='missing'?r.submitDate:'','图片数量':data.images.filter(i=>i.recordId===r.id).length});
  row['备注']=r.note;return row;});}
function exportsFor(records,selection='all'){return Object.fromEntries(exportKinds(selection).map(([kind,label])=>{const rows=exportRows(kind,records.filter(r=>data.activities.find(a=>a.id===r.activityId)?.kind===kind));return [label,rows.length?rows:[{'说明':'暂无记录'}]];}));}
function exportModuleDialog(){const a=currentActivity();modal('导出 Excel',`<p class="help">选择需要导出的范围。全部记录遵循顶部班级选择。</p><div class="field"><span>导出范围</span><select id="export-scope"><option value="filtered">本场当前筛选结果（${recordRows(a).length} 人）</option><option value="current">本场全部学生</option><option value="all">本模块全部场次</option></select></div><div class="dialog-actions">${btn('导出','export-module-confirm','','primary')}</div>`);}
function exportKinds(selection='all'){return Object.entries(labels).filter(([kind])=>selection==='all'||kind===selection);}
function exportOptions(current='all'){return [['all','全部'],['hw','作业'],['dict','默写'],['quiz','小测']].map(([v,label])=>option(v,label,current)).join('');}
function exportDialog(target){modal('选择导出内容',`<p class="help">${target==='student'?'导出当前学生，沿用档案中选择的日期范围。':'导出全部班级的学习记录。'}</p><label class="field"><span>导出内容</span><select id="export-kind">${exportOptions()}</select></label><div class="dialog-actions">${btn('取消','close')}${btn('导出 Excel','export-selected',`data-target="${target}"`,'primary')}</div>`);}
function studentExportSummary(s,selection){const sum=T.summary(data,s.id,from,to),row={'姓名':s.name,'班级':className(s.classId),'学号':s.number,'性别':genderLabel(s.gender),'开始日期':from||'不限','结束日期':to||'不限'};
  if(selection==='all'||selection==='dict')row['加权默写通过率(%)']=sum.dict;
  if(selection==='all'||selection==='quiz'){row['有效小测次数']=sum.quizzes.length;row['最近小测得分率(%)']=sum.quizzes.at(-1)?.value??null;}
  if(selection==='all'||selection==='hw')Object.assign(row,{'作业完成率(%)':sum.hw,'初次未完成次数':sum.missing,'已补交次数':sum.submitted});
  return row;
}
function reportMarkup(s,images,selection='all'){
  const sum=T.summary(data,s.id,from,to),has=kind=>selection==='all'||selection===kind;
  const stats=[],details=[],notes=[];
  if(has('dict')){stats.push(`<div><span>加权默写通过率</span><strong>${pct(sum.dict)}</strong></div>`);details.push(`有效默写 ${sum.dictCount} 次`);notes.push('默写加权通过率：p = 1，p- = 0.5，f = 0，未参加排除，重默不改变首次结果。');}
  if(has('quiz')){stats.push(`<div><span>最近小测得分率</span><strong>${sum.quizzes.length?pct(sum.quizzes.at(-1).value):'暂无数据'}</strong></div>`);details.push(`有效小测 ${sum.quizzes.length} 次`);notes.push('小测得分率 = 得分 / 总分；缺考排除，pp 表示百分点。同分并列名次，年级仅包含同一场关联班级，尚未录齐时为暂定名次。');}
  if(has('hw')){stats.push(`<div><span>作业完成率</span><strong>${pct(sum.hw)}</strong></div>`);details.push(`作业初次未完成 ${sum.missing} 次，其中已补交 ${sum.submitted} 次`);notes.push('作业完成率含补交，免交排除。');}
  return `<article class="report"><header class="report-head"><div class="eyebrow">${esc(appName())} · STUDENT LEARNING REPORT</div><h1>${esc(s.name)}的${selection==='all'?'学习成长':labels[selection]}记录</h1><p>${esc(className(s.classId))} · 学号 ${esc(s.number)||'未填写'}<br><span class="help">记录范围：${from||'最早记录'} 至 ${to||'最新记录'} · 生成于 ${today()}</span></p></header><div class="report-stats">${stats.join('')}</div><p class="help">${details.join(' · ')}。</p>${has('quiz')?`<h2>小测成长曲线 · ${trendLabels[trendMode]}</h2><p class="help">${trendHelp()}</p>${chart(sum.quizzes)}`:''}${studentTables(s.id,true,images&&has('hw'),selection)}<footer class="report-footer">${esc(appName())} · 每一份成长，都值得记录。<br>${notes.join('')}</footer></article>`;
}
function reportDialog(){const s=data.students.find(s=>s.id===studentId);modal('学生报告预览',`<div class="toolbar"><label>导出内容 <select id="report-kind">${exportOptions(reportKind)}</select></label><label id="report-trend-label" ${reportKind==='all'||reportKind==='quiz'?'':'hidden'}>趋势指标 <select id="report-trend-mode">${trendOptions()}</select></label><label id="report-images-label" ${reportKind==='all'||reportKind==='hw'?'':'hidden'}><input type="checkbox" id="report-images" ${includeImages?'checked':''}> 附上作业图片</label><span class="spacer"></span>${btn('打印 / 保存为 PDF','print-report','','primary')}</div><p class="help">打印时选择 A4、另存为 PDF。建议关闭浏览器自带页眉和页脚。</p><div id="report-preview">${reportMarkup(s,includeImages,reportKind)}</div>`,true);}
function importDialog(kind){importState={kind,rows:[],checked:[],errors:[],activityId:kind==='scores'?currentActivity()?.id:null};modal(kind==='roster'?'导入学生名单':'导入小测成绩',`<p class="help">${kind==='roster'?'必填列：班级、姓名；选填：学号、性别（男 / 女）。未填性别的学生计入整体平均分，不计入男、女生分组。':'必填列：姓名或学号、成绩；选填：班级。缺考填“缺考”，空白表示未录入。仅导入当前场次学生，不影响未列出的学生。'}</p><div class="row" style="margin-bottom:15px">${btn('下载模板',kind==='roster'?'roster-template':'score-template')}</div>${kind==='roster'?'<label class="help"><input type="checkbox" id="import-gender-only"> 仅更新已有学生性别（不新增学生，按班级＋学号匹配；无学号时按姓名匹配）</label>':''}<label class="file-label">选择 Excel 文件<input id="import-file" type="file" accept=".xlsx,.xls,.csv"></label><p class="help">读取第一个工作表；先预览并检查，再确认导入。文件最大 20 MB。</p><div id="import-preview"></div>`,true);}
function validateImport(){const st=importState,seen=new Set();st.checked=[];st.errors=[];const a=data.activities.find(a=>a.id===st.activityId);if(st.kind==='scores'&&!a)throw Error('小测场次已不存在');
  st.rows.forEach((row,i)=>{let error='',item=null;try{if(st.kind==='roster'){
      const cn=String(row['班级']??'').trim(),name=String(row['姓名']??'').trim(),number=String(row['学号']??'').trim();if(!cn||!name)throw Error('班级和姓名不能为空');if([cn,name,number].some(x=>x.length>80))throw Error('字段过长，最多 80 字');
      const gender=T.parseGender(row['性别']);
      const c=data.classes.find(c=>c.name===cn),key=cn+'|'+(number?'#'+number:name);if(seen.has(key))throw Error('文件中存在重复学号或未填学号的同名行');seen.add(key);
      if(st.genderOnly){if(!c)throw Error('找不到对应班级');if(!String(row['性别']??'').trim())throw Error('更新性别时请填写男、女或未填写');const existing=T.matchStudent(data,row,c.id);item={studentId:existing.id,gender};}
      else{if(c&&data.students.some(s=>s.classId===c.id&&(number?s.number===number:s.name===name)))throw Error('学生已存在；更新性别请勾选仅更新模式');item={className:cn,name,number,gender};}
    }else{
      const cn=String(row['班级']??'').trim();if(cn&&cn!==className(a.classId))throw Error('班级与当前小测不一致');const s=T.matchStudent(data,row,a.classId);if(!a.studentIds.includes(s.id))throw Error('学生不在本场参与名单');if(seen.has(s.id))throw Error('同一学生出现多次');seen.add(s.id);
      const raw=String(row['成绩']??'').trim();if(raw==='缺考')item={studentId:s.id,status:'absent',score:null};else if(raw==='')item={studentId:s.id,status:'blank',score:null};else{const score=Number(raw);if(!Number.isFinite(score)||score<0||score>a.total)throw Error(`成绩须为 0 至 ${a.total}`);item={studentId:s.id,status:'score',score};}
    }}catch(e){error=e.message;}st.checked.push(item);st.errors.push(error);
  });
}
function importPreview(){validateImport();const st=importState,cols=st.kind==='roster'?['班级','姓名','学号','性别']:['班级','姓名','学号','成绩'];$('#import-preview').innerHTML=`<div class="divider"></div><div class="row spread"><strong>${st.rows.length} 行 · ${st.errors.filter(Boolean).length} 行需修正</strong><span class="help">可直接在下表修正后重新检查</span></div><div class="table-wrap" style="max-height:380px;margin-top:12px"><table><thead><tr><th>行</th>${cols.map(c=>`<th>${c}</th>`).join('')}<th>检查结果</th><th></th></tr></thead><tbody>${st.rows.map((r,i)=>`<tr><td>${i+2}</td>${cols.map(c=>`<td><input style="width:125px" aria-label="第${i+2}行${c}" data-import-row="${i}" data-import-col="${c}" value="${esc(r[c])}"></td>`).join('')}<td class="${st.errors[i]?'error-text':'help'}">${esc(st.errors[i]||'可以导入')}</td><td>${btn('移除','import-remove',`data-index="${i}"`,'small ghost')}</td></tr>`).join('')}</tbody></table></div><div class="dialog-actions">${btn('重新检查','import-check')}${btn(st.kind==='scores'?'确认覆盖所列学生成绩':'确认导入','import-confirm',st.errors.some(Boolean)||!st.rows.length?'disabled':'','primary')}</div>`;}
async function readImport(file){if(file.size>20*1024*1024)throw Error('文件超过 20 MB');if(!globalThis.XLSX)throw Error('Excel 库未加载');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(!matrix.length)throw Error('表格为空');const headers=matrix[0].map(x=>String(x).trim());const required=importState.kind==='roster'?['班级','姓名']:['成绩'];if(required.some(h=>!headers.includes(h))||importState.kind==='scores'&&!headers.includes('姓名')&&!headers.includes('学号'))throw Error('列名不匹配，请使用提供的模板');if(new Set(headers.filter(Boolean)).size!==headers.filter(Boolean).length)throw Error('表头含重复列名');importState.rows=matrix.slice(1).filter(row=>row.some(v=>String(v).trim())).map(row=>Object.fromEntries(headers.filter(Boolean).map(h=>[h,String(row[headers.indexOf(h)]??'').trim()])));if(importState.rows.length>5000)throw Error('单次最多导入 5000 行');importPreview();}
async function confirmImport(){validateImport();if(importState.errors.some(Boolean)||!importState.rows.length)throw Error('请先修正导入错误');const st=importState;if(st.kind==='roster'){st.checked.forEach(x=>{if(st.genderOnly){data.students.find(s=>s.id===x.studentId).gender=x.gender;return;}let c=data.classes.find(c=>c.name===x.className);if(!c){c={id:T.uid(),name:x.className};data.classes.push(c);}data.students.push({id:T.uid(),classId:c.id,name:x.name,number:x.number,gender:x.gender,active:true});});}else{st.checked.forEach(x=>{const r=T.record(data,st.activityId,x.studentId);r.status=x.status;r.score=x.score;});}await save();close();if(st.kind==='roster'){view='students';classId='';studentId='';search='';}render();toast(`已导入 ${st.checked.length} 条记录`);importState=null;}
function rosterTemplate(){workbook({'学生名单':[{'班级':'','姓名':'','学号':'','性别':''}]},'学生名单导入模板');}
function scoreTemplate(){const a=currentActivity();if(!a||a.kind!=='quiz')throw Error('请先打开一场小测');workbook({'小测成绩':a.studentIds.map(id=>{const s=data.students.find(s=>s.id===id);return {'班级':className(a.classId),'姓名':s.name,'学号':s.number,'成绩':''};})},`${a.name}-成绩导入模板`);}
function restoreDialog(){modal('恢复完整备份',`<p class="help">恢复会替换当前全部数据。建议先导出当前备份。选择文件后会展示摘要，不会立即恢复。</p>${btn('先导出当前备份','backup')}<label class="file-label" style="margin-top:15px">选择备份文件<input type="file" id="restore-file" accept=".json"></label><div id="restore-preview"></div>`);}
let restoreData=null;
async function handleAction(el){const action=el.dataset.action,id=el.dataset.id;
  if(action==='close'){close();return;}
  if(action==='nav'){view=el.dataset.view;studentId='';search='';filter='';sort='name';render();return;}
  if(action==='choose-activity')return chooseActivity();
  if(action==='activity-new')return activityForm(el.dataset.kind);
  if(action==='rename-workspace')return workspaceNameForm();
  if(action==='quiz-link')return quizLinkDialog(id);
  if(action==='class-new'||action==='class-edit')return classForm(id);
  if(action==='student-new'||action==='student-edit')return studentForm(id);
  if(action==='profile'){view='students';studentId=id;from='';to='';close();render();return;}
  if(action==='student-back'){studentId='';render();return;}
  if(action==='range-clear'){from='';to='';render();return;}
  if(action==='open-activity'||action==='open-issue'){const a=data.activities.find(x=>x.id===id);view=a.kind;selected[view]=id;classId=a.classId;search=action==='open-issue'?nameOf(el.dataset.student):'';filter=action==='open-issue'&&el.dataset.type==='correction'?'own-correction':'';sort='name';close();render();return;}
  if(action==='dict-status'){const r=data.records.find(x=>x.id===id);r.status=el.dataset.value;if(r.status!=='f'){r.retake='pending';r.retakeDate='';}await save();render();return;}
  if(action==='record-detail')return detail(id);
  if(action==='photos')return photos(id);
  if(action==='image-view'){const i=data.images.find(x=>x.id===id);modal(esc(i.name),`<img src="${i.data}" style="max-width:100%;max-height:65vh;display:block;margin:auto" alt="${esc(i.name)}"><div class="dialog-actions">${btn('返回图片管理','photos',`data-id="${i.recordId}"`)}</div>`,true);return;}
  if(action==='image-delete'){data.images=data.images.filter(x=>x.id!==id);await save();render();photos(el.dataset.record);return;}
  if(action==='issues')return showIssues(el.dataset.type);
  if(action==='delete-activity'){const a=data.activities.find(x=>x.id===id);modal('删除这场记录？',`<p>「${esc(a.name)}」及其学生记录、作业图片将一并删除，此操作无法撤销。</p><div class="dialog-actions">${btn('取消','close')}${btn('确认删除','delete-confirm',`data-id="${id}"`,'danger')}</div>`);return;}
  if(action==='delete-confirm'){const ids=new Set(data.records.filter(r=>r.activityId===id).map(r=>r.id));data.images=data.images.filter(i=>!ids.has(i.recordId));data.records=data.records.filter(r=>r.activityId!==id);data.activities=data.activities.filter(a=>a.id!==id);await save();close();render();return;}
  if(action==='roster-template')return rosterTemplate();
  if(action==='score-template')return scoreTemplate();
  if(action==='import-roster')return importDialog('roster');
  if(action==='import-scores')return importDialog('scores');
  if(action==='import-check')return importPreview();
  if(action==='import-remove'){importState.rows.splice(Number(el.dataset.index),1);return importPreview();}
  if(action==='import-confirm')return confirmImport();
  if(action==='export-roster'){workbook({'学生名单':data.students.filter(s=>!classId||s.classId===classId).map(s=>({'班级':className(s.classId),'姓名':s.name,'学号':s.number,'性别':genderLabel(s.gender),'状态':s.active?'在读':'停用'}))},'学生名单');return;}
  if(action==='export-module')return exportModuleDialog();
  if(action==='export-module-confirm'){const scope=$('#export-scope').value,a=currentActivity();const records=scope==='filtered'?recordRows(a).map(x=>x.r):scope==='current'?data.records.filter(r=>r.activityId===a.id):data.records.filter(r=>{const x=data.activities.find(a=>a.id===r.activityId);return x.kind===view&&(!classId||x.classId===classId);});if(!records.length)throw Error('此范围没有可导出的记录');workbook({[labels[view]]:exportRows(view,records)},`${labels[view]}-${scope==='all'?'全部场次':a.name}`);close();return;}
  if(action==='export-all')return exportDialog('all');
  if(action==='export-student')return exportDialog('student');
  if(action==='export-selected'){
    const selection=$('#export-kind').value,title=selection==='all'?'全部学习记录':`${labels[selection]}记录`;
    if(el.dataset.target==='student'){const s=data.students.find(s=>s.id===studentId);workbook({'学生概览':[studentExportSummary(s,selection)],...exportsFor(T.entries(data,s.id,null,from,to).map(x=>x.r),selection)},`${s.name}-${title}`);}
    else workbook(exportsFor(data.records,selection),title);
    close();return;
  }
  if(action==='report')return reportDialog();
  if(action==='print-report'){const s=data.students.find(s=>s.id===studentId);$('#print-root').innerHTML=reportMarkup(s,includeImages,reportKind);await Promise.all([...$('#print-root').querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));const old=document.title;document.title=`${s.name}-${reportKind==='all'?'学习成长':labels[reportKind]}报告`;window.print();document.title=old;return;}
  if(action==='backup'){download(new Blob([JSON.stringify({...data,exportedAt:new Date().toISOString()})],{type:'application/json'}),` ${appName()}完整备份-${today()}.json`.trim().replace(/[\\/:*?"<>|]/g,'_'));toast('完整备份已下载，包含图片');return;}
  if(action==='restore')return restoreDialog();
  if(action==='restore-confirm'){if(!$('#restore-agree').checked)throw Error('请勾选确认替换当前数据');T.validateBackup(restoreData);data=structuredClone(restoreData);data.settings??={appName:'紫笺'};delete data.exportedAt;await save();restoreData=null;close();classId='';selected={};studentId='';view='overview';render();toast('备份已恢复');return;}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)handleAction(el).catch(err=>{console.error(err);toast(err.message);});});
let searchTimer;
document.addEventListener('input',e=>{const el=e.target;if(['record-search','student-search'].includes(el.id)){search=el.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const start=el.selectionStart,id=el.id;render();const input=$('#'+id);input?.focus();input?.setSelectionRange(start,start);},200);}if(el.dataset.importRow!==undefined){importState.rows[Number(el.dataset.importRow)][el.dataset.importCol]=el.value;const b=$('[data-action="import-confirm"]');if(b)b.disabled=true;}});
document.addEventListener('change',e=>handleChange(e.target).catch(err=>{console.error(err);toast(err.message);}));
async function handleChange(el){
  if(el.id==='trend-mode'){trendMode=el.value;render();return;}
  if(el.id==='report-trend-mode'){trendMode=el.value;$('#report-preview').innerHTML=reportMarkup(data.students.find(s=>s.id===studentId),includeImages,reportKind);return;}
  if(el.id==='new-quiz-group'){const form=$('#activity-form'),target=data.activities.find(a=>a.id===el.value);for(const key of ['name','total']){form.elements[key].readOnly=!!target;if(target)form.elements[key].value=target[key];}if(target)form.elements.date.value=target.date;return;}
if(el.id==='class-filter'){classId=el.value;search='';studentId='';filter='';render();return;}
  if(el.id==='activity-select'){selected[view]=el.value;search='';filter='';render();return;}
  if(el.id==='record-filter'){filter=el.value;render();return;}
  if(el.id==='record-sort'){sort=el.value;render();return;}
  if(el.id==='date-from'||el.id==='date-to'){const value=el.value;if(el.id==='date-from'){if(value&&to&&value>to){el.value=from;throw Error('开始日期不能晚于结束日期');}from=value;}else{if(value&&from&&value<from){el.value=to;throw Error('结束日期不能早于开始日期');}to=value;}render();return;}
  if(el.id==='report-kind'){reportKind=el.value;$('#report-trend-label').hidden=reportKind!=='all'&&reportKind!=='quiz';$('#report-images-label').hidden=reportKind!=='all'&&reportKind!=='hw';$('#report-preview').innerHTML=reportMarkup(data.students.find(s=>s.id===studentId),includeImages,reportKind);return;}
  if(el.id==='report-images'){includeImages=el.checked;$('#report-preview').innerHTML=reportMarkup(data.students.find(s=>s.id===studentId),includeImages,reportKind);return;}
  if(el.id==='import-gender-only'){importState.genderOnly=el.checked;if(importState.rows.length)importPreview();return;}
  if(el.id==='import-file'){if(el.files[0])await readImport(el.files[0]);return;}
  if(el.id==='restore-file'){if(!el.files[0])return;restoreData=null;$('#restore-preview').innerHTML='';if(el.files[0].size>500*1024*1024)throw Error('备份超过 500 MB');const d=JSON.parse(await el.files[0].text());T.validateBackup(d);restoreData=d;$('#restore-preview').innerHTML=`<div class="divider"></div><p>工作台名称：${esc(d.settings?.appName||'紫笺')}</p><p>备份内容：${d.classes.length} 个班级、${d.students.length} 位学生、${d.activities.length} 场活动、${d.records.length} 条记录、${d.images.length} 张图片。</p><label><input type="checkbox" id="restore-agree"> 我已备份当前数据，确认用此备份替换</label><div class="dialog-actions">${btn('恢复并替换','restore-confirm','','primary')}</div>`;return;}
  if(el.id==='photo-upload'){el.disabled=true;try{const files=Array.from(el.files),items=[];for(const file of files)items.push({id:T.uid(),recordId:el.dataset.record,name:file.name,tag:'good',data:await compressImage(file)});data.images.push(...items);await save();render();photos(el.dataset.record);toast(`已保存 ${items.length} 张图片`);}finally{el.disabled=false;}return;}
  if(el.dataset.image){data.images.find(i=>i.id===el.dataset.image).tag=el.value;await save();render();return;}
  if(el.dataset.record&&el.dataset.field){const r=data.records.find(r=>r.id===el.dataset.record),field=el.dataset.field,a=data.activities.find(a=>a.id===r.activityId);let value=el.type==='checkbox'?el.checked:el.value;
    if(field==='score'){if(value===''){r.score=null;r.status='blank';}else{const n=Number(value);if(!Number.isFinite(n)||n<0||n>a.total){el.value=r.score??'';throw Error(`成绩须为 0 至 ${a.total}`);}r.score=n;r.status='score';}}
    else if(field==='status'&&a.kind==='quiz'){if(value==='score'&&r.score===null){el.value=r.status;throw Error('请先输入成绩');}r.status=value;if(value!=='score')r.score=null;}
    else{r[field]=value;if(field==='retake'){r.retakeDate=value==='pending'?'':r.retakeDate||today();}if(field==='submitted'){r.submitDate=value?r.submitDate||today():'';}if(field==='status'&&a.kind==='hw'&&value!=='missing'){r.submitted=false;r.submitDate='';}}
    await save();if(field!=='note')render();return;
  }
}
document.addEventListener('submit',e=>{e.preventDefault();handleSubmit(e.target).catch(err=>{console.error(err);toast(err.message);});});
async function handleSubmit(form){const f=Object.fromEntries(new FormData(form));
  if(form.id==='workspace-name-form'){const name=f.appName.trim();if(!name||name.length>20)throw Error('请输入 1–20 个字符的工作台名称');data.settings={...data.settings,appName:name};await save();close();render();toast('工作台名称已保存');return;}
  if(form.id==='quiz-link-form'){if(f.targetId!=='keep')T.linkQuiz(data,form.dataset.id,f.targetId);await save();close();render();toast('跨班统计关联已更新');return;}
  if(form.id==='activity-form'){const a=T.createActivity(data,{kind:form.dataset.kind,classId:f.classId,date:f.date,name:f.name,total:f.total,joinQuizId:f.joinQuizId});await save();view=a.kind;classId=a.classId;selected[view]=a.id;search='';filter='';close();render();toast('记录已创建');}
  if(form.id==='class-form'){const name=f.name.trim();if(!name)throw Error('班级名称不能为空');if(data.classes.some(c=>c.name===name&&c.id!==form.dataset.id))throw Error('已存在同名班级');const c=data.classes.find(c=>c.id===form.dataset.id);if(c)c.name=name;else data.classes.push({id:T.uid(),name});await save();close();render();}
  if(form.id==='student-form'){const name=f.name.trim(),number=f.number.trim();if(!name)throw Error('姓名不能为空');let c=data.classes.find(c=>c.id===f.classId);let newClass=null;if(f.newClass?.trim()){c=data.classes.find(c=>c.name===f.newClass.trim());if(!c){c={id:T.uid(),name:f.newClass.trim()};newClass=c;}}if(!c)throw Error('请选择或新建班级');if(number&&data.students.some(s=>s.classId===c.id&&s.number===number&&s.id!==form.dataset.id))throw Error('该班学号已存在');if(newClass)data.classes.push(newClass);const s=data.students.find(s=>s.id===form.dataset.id),values={name,number,classId:c.id,gender:T.parseGender(f.gender),active:f.active==='true'};if(s)Object.assign(s,values);else data.students.push({id:T.uid(),...values});await save();close();render();toast('学生资料已保存');}
}
openDB().then(()=>{T.validateBackup(data);render();}).catch(err=>{$('#app').innerHTML=`<div class="loading"><h2>暂时无法打开本地数据</h2><p>${esc(err.message)}</p><p>请使用允许本地存储的普通浏览器窗口重新打开，避免使用隐私模式。</p></div>`;});
